### ISSUE TITLE
The F# record type produced by proto file has recursive namespace statement

### ISSUE THREAD

**Issue by bugra** [jet/falanx#94] opened 2018-12-24 15:38 UTC
**Describe the bug**
- I am using the `Falanx.Sdk 0.4.0-alpha2` and the produced F# record type module has recursive namespace statement.

This is not a bug per se, but for our projects, we use multiple files that share a common namespace. If we were to use recursive namespaces across all of our protobuff generated record types, that may remove the dependency order that is enforced on the namespace itself.

**Actual behavior**
This is what we see in the namespace definition of the produced F# record type

```fsharp
namespace rec ProfX.SearchApi

open System
open System.Collections.Generic
open Newtonsoft.Json.Linq
open Fleece.Newtonsoft
```

**Environment (please complete the following information):**
 - OS: osx
 - Framework:  netstandard2.0, net462

**Additional context**

**Comment by 7sharp9** [comment] 2019-01-02 09:56
Yeah this is by design, `oneOf` types require a rec definition as they have the same module name as the record they are created in.  Its possible I could suppress this if the referenced proto file has no `oneOfs` defined within it...

**Comment by enricosada** [comment] 2019-01-04 17:43
@bugra i checked with some sample proj using prec docs examples](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/namespaces#recursive-namespaces) and the `rec` is valid for that file only.

Others files with same namespace doesnt automatically become `rec`, and are normal as usual

Closing, because having `rec` doesnt interfer with multiple files with same namespace in same project, and dependency order of others is preserved.

**Closed by enricosada** 2019-01-04 17:43 UTC
Labels: by design
